pipeline {
    agent any

    stages {
        stage('Git-Checkout') {           
            steps {
        	git branch: 'main', url: 'https://github.com/fatih76/JenkinsGitExample.git'
            }
        }    
    
        stage('Datei') {
            steps {
                echo 'Zu testende Datei:'
                sh ''' cd /home/fatih/Fatih/IT-Lernen/Programmierung/Jenkins/JenkinsGitExample/hello
                python3.12 hello.py
                pwd '''
            }
        }   
    
        stage('Unittest') {
            steps {                
                sh ''' echo 'Unittest-Datei'
                cd /home/fatih/Fatih/IT-Lernen/Programmierung/Jenkins/JenkinsGitExample/hello
                python3.12 test_hello.py '''
            }
        }    
   
        stage('Deploy') {
            steps {
                echo 'Deploying app'
                echo 'echo OK!'
            }
        }  
    }
    
    post {
        failure {
            echo 'Bauen war nicht erfolgreich'
        }
        
        success {
            sh ''' cd /var/lib/jenkins/workspace
            rm -rf JenkinsGitExample/ JenkinsGitExample@tmp
            cd /home/fatih/Fatih/IT-Lernen/Programmierung/Jenkins
            cp -r JenkinsGitExample /var/lib/jenkins/workspace
            '''
        }
    }
}
